---
jenkins_cli_plugins:
  - gearman-plugin
  - zmq-event-publisher

jenkins_cli_groovy_dir: files/jenkins/var/lib/jenkins/.scripts/

jenkins_jobs_project_config_dir: /home/pabelanger/git/pabelanger/config/jenkins/jobs/

nginx_config_include_files: files/jenkins/etc/nginx/conf.d/

ssh_user_name: jenkins
ssh_user_home: /var/lib/jenkins
