---
logrotate_configs:
  - name: zuul
    log: /var/log/zuul/*.log
    options:
      - compress
      - missingok
      - rotate 7
      - daily
      - notifempty

zuul_config_gearman_server_listen_address: 0.0.0.0
zuul_config_gerrit_server: review.openstack.org
zuul_config_gerrit_user: ufuktron

zuul_config_merger_git_user_email: ufuktron@gmail.com
zuul_config_merger_git_user_name: ufuktron

zuul_project_config_dir: /home/pabelanger/git/pabelanger/config/zuul/

ssh_user_name: zuul
ssh_user_home: /var/lib/zuul
ssh_known_hosts_content: |
  [review.openstack.org]:29418 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfsIj/jqpI+2CFdjCL6kOiqdORWvxQ2sQbCzSzzmLXic8yVhCCbwarkvEpfUOHG4eyB0vqVZfMffxf0Yy3qjURrsroBCiuJ8GdiAcGdfYwHNfBI0cR6kydBZL537YDasIk0Z3ILzhwf7474LmkVzS7V2tMTb4ZiBS/jUeiHsVp88FZhIBkyhlb/awAGcUxT5U4QBXCAmerYXeB47FPuz9JFOVyF08LzH9JRe9tfXtqaCNhlSdRe/2pPRvn2EIhn5uHWwATACG9MBdrK8xv8LqPOik2w1JkgLWyBj11vDd5I3IjrmREGw8dqImqp0r6MD8rxqADlc1elfDIXYsy+TVH
